@startuml
start
:Access link in verification email;
if (Token is valid?) then (yes)
  :Check user email in token and compare email in the database;
  if (User exists?) then (yes)
    :Update user as activated;
    :Account is activated;
    stop
  else (no)
    :Send message User not exists;
    stop
  endif
else (no)
  :Send bad request;
  stop
endif
@enduml
