@startuml
|Client|
start
:Parent navigates to the "Daily Meal" section;
:Parent selects "Edit" button;
:Parent selects "Add" button;
:Parents picks mealtime from the time picker;
:Parent enters the dish name to find;
|Server|
:Return a list of matching name dishes;
|Client|
:Parent selects the desired meal;
|Server|
:Extract the meal nutritional information from the database;
:Using MCDA to calculate the nutritional value of the meal;
:Categorize the meal as Main Course or Side Dish using PDV checker;
:Get the meal type;
if (Selected meal type) then (Main Course) 
    if(The meal time is same with a meal time session in the database) then (yes)
        :Removes the existing meal detail in the database;
        :Adds the selected meal to the existing meal plan;
        else (no)
        :Creates a new meal detail as Main Course in the database;
        :Adds the selected meal to the existing meal plan;
    endif
else (Side Dish)
    if (The meal time is same with a meal with time session in the database) then (yes)
        :Remove the existing meal detail in the database;
        :Adds the selected meal to the existing meal plan;
    else (no)
        :Creates a new meal detail in the database;
        :Adds the selected meal to the existing meal plan;
    endif
endif
|Client|
:Display the selected meal is added to the meal plan;
stop
@enduml

